services:
  justice:
    image: justice-ms-test
    privileged: true
    container_name: gump-justice-backend
    volumes:
      - ./uploads:/uploads
      - /etc/resolv.conf:/etc/resolv.con
    restart: on-failure
    depends_on:
      - eureka-server
      - justice-database
    networks:
      gump-network:
        aliases:
          - justice
    dns:
      - 8.8.8.8  # Add DNS servers to ensure resolution works
      - 8.8.4.4
    ports:
      - 8085:8085
    env_file:
      - .env
    environment:
      - APP_URL=https://gump-gateway.yulpay.com
      - SPRING_DATASOURCE_URL=jdbc:postgresql://justice-database:5432/gump
      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://eureka-server:8761/eureka/
      - VPN_PASSWORD=L@PAtr!0Dab0rt2024
      - VPN_USERNAME=aziz.zorom
      - VPN_SERVER=196.13.207.201
      - SERVER_CERT=pin-sha256:sFLHgJ3eNOnt4dJ4XMylztoDXlyMraNydmGWxxfUpE8=
      - JUSTICE_SERVICE_USERNAME=gump@gmail.com
      - JUSTICE_SERVICE_PASSWORD=123456


  eureka-server:
    image: ghcr.io/yulcom-technologies-burkina/gump-eureka-server:$COMMIT_SHA
    container_name: gump-drtss-eureka-server
    networks:
      - gump-network
    ports:
      - 8761:8761


  justice-database:
    image: postgres:16.4
    networks:
      - gump-network
    volumes:
      - justice-data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=gump
      - POSTGRES_PASSWORD=gump
      - POSTGRES_HOST_AUTH_METHOD=trust
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U $${POSTGRES_USER}']
      interval: 5s
      timeout: 5s
      retries: 10
    ports:
      - 5437:5432

volumes:
  justice-data:

networks:
  gump-network:
