spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5431/gump
    username: gump
    password: gump
  application:
    name: drtss-ms

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8082
  servlet:
    context-path: /api

app:
  url: http://localhost:8082/api
