spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5431/gump
    username: gump
    password: gump
  servlet:
    multipart:
      max-file-size: 10MB

  application:
    name: drtss-ms
  config:
    import: optional:configserver:http://localhost:8888

keycloak:
  auth-server-url: https://sso.kulturman.com
  realm: gump

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8082
  servlet:
    context-path: /api

app:
  front:
    url: https://gump.yulpay.com
  url: http://localhost:8082/api
