spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${keycloak.auth-server-url}/realms/${keycloak.realm}
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://195.35.48.198:5429/gump
    username: gump
    password: gump
  application:
    name: users-ms

keycloak:
  auth-server-url: https://sso.kulturman.com
  realm: gump
  client: gump
  clientId: 513e476c-6bfb-4878-b0fb-cbfb36c401ea

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

server:
    port: 8081
    servlet:
        context-path: /api

jwt:
  auth:
    converter:
      resource-id: gump
      principle-attribute: preferred_username

app:
  url: http://localhost:8081/api
