spring:
  application:
    name: notification-ms
  mail:
    host: smtp.gmail.com
    port: 587
    username: mandson1er@gmail.com
    password: hvbv qrgc puyn deqe
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8084
  servlet:
    context-path: /api
