spring:
  application:
    name: notifcation-ms
  mail:
    host: localhost
    port: 1025
    username: your_email@gmail.com
    password: your_password
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
server:
  port: 8084
