spring:
  application:
    name: notification-ms
  mail:
    host: localhost
    port: 1025
    username: your_email@gmail.com
    password: your_password
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8084
  servlet:
    context-path: /api
