eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: "http://localhost:9090/realms/myrealm"
  cloud:
    gateway:
      mvc:
        routes:
          - id: tresor-ms
            uri: http://localhost:8080
            predicates:
              - Path=/tresor-ms/**
            filters:
              - StripPrefix=1
              - PrefixPath=/api
  application:
    name: gateway
  config:
    import: optional:configserver:http://localhost:8888
server:
  port: 9090
