eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false

keycloak:
    auth-server-url: http://localhost:9080
    realm: gump

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${keycloak.auth-server-url}/realms/${keycloak.realm}
  cloud:
    gateway:
      mvc:
        routes:
          - id: tresor-ms
            uri: http://localhost:8080
            predicates:
              - Header=service, tresor-ms
            filters:
              - StripPrefix=1
              - PrefixPath=/api

          - id: drtss-ms
            uri: http://localhost:8082
            predicates:
              - Header=service, drtss-ms
            filters:
              - StripPrefix=1
              - PrefixPath=/api
  application:
    name: gateway
  config:
    import: optional:configserver:http://localhost:8888
server:
  port: 9090
