spring:
  cloud:
    gateway:
      mvc:
        routes:
          - id: tresor-ms
            uri: http://localhost:8080
            predicates:
              - Path=/tresor-ms/**
            filters:
              - StripPrefix=1
              - PrefixPath=/api
  application:
    name: gateway
  config:
    import: optional:configserver:http://localhost:8888
server:
  port: 9090
