spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://195.35.48.198:5430/gump
    username: gump
    password: gump
  application:
    name: tresor-ms
server:
  port: 8080
  servlet:
    context-path: /api

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

app:
  front:
    url: https://gump.yulpay.com
  url: http://localhost:9090
