eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false

keycloak:
  auth-server-url: http://localhost:9080
  realm: gump

spring:
  main:
    web-application-type: reactive
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${keycloak.auth-server-url}/realms/${keycloak.realm}
  cloud:
    gateway:
      globalcors:
        add-to-simple-url-handler-mapping: true
        corsConfigurations:
          '[/**]':
            allowedOrigins: ""
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders:
              - "*"
            allowCredentials: true
      routes:
        - id: tresor-ms
          uri: ${TRESOR_MS_URI:http://localhost:8080}
          predicates:
            - Query=service, tresor-ms
          filters:
            - StripPrefix=1
            - PrefixPath=/api

        - id: drtss-ms
          uri: ${DRTSS_MS_URI:http://localhost:8082}
          predicates:
            - Query=service, drtss-ms
          filters:
            - StripPrefix=1
            - PrefixPath=/api
          metadata:
            cors:
              allowedOrigins: ""
              allowedMethods:
                - GET
                - POST
                - PUT
                - DELETE
                - OPTIONS
              allowedHeaders:
                - "*"
              allowCredentials: true

        - id: users-ms
          uri: ${USERS_MS_URI:http://localhost:8081}
          predicates:
            - Query=service, users-ms
          filters:
            - StripPrefix=1
            - PrefixPath=/api
  application:
    name: reactive-gateway
  config:
    import: optional:configserver:http://localhost:8888
server:
  port: 9091
