name: Build and deploy micro-services

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    strategy:
      matrix:
        ms: [drtss-ms, tresor-ms, gateway, eureka-server]
    defaults:
      run:
        working-directory: ${{matrix.ms}}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
          server-id: github
          server-username: GITHUB_ACTOR
          server-password: GITHUB_TOKEN
      - run: ls

      - name: Build ${{matrix.ms}}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: mvn clean install -s ../settings.xml

      - name: Log in to registry
        run: echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u kulturman --password-stdin

      - name: build-docker-image
        run: |
          docker build --tag ghcr.io/yulcom-technologies-burkina/gump-${{matrix.ms}}:latest .
          docker build --tag ghcr.io/yulcom-technologies-burkina/gump-${{matrix.ms}}:${{github.sha}} .
          docker push ghcr.io/yulcom-technologies-burkina/gump-${{matrix.ms}}:latest
          docker push ghcr.io/yulcom-technologies-burkina/gump-${{matrix.ms}}:${{github.sha}}

  deploy:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: ls
      - name: Copy docker-compose file to remote server
        uses: appleboy/scp-action@master
        with:
          passphrase: ${{ secrets.SSH_PASSPHRASE }}
          host: ${{ vars.REMOTE_HOST }}
          username: ${{ vars.REMOTE_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "docker-compose-dev.yml,realm-config,keycloak.yml"
          target: "/home/${{ vars.REMOTE_HOST }}/gump"
      - run: ls
      - name: Deploy to dev environnement
        uses: appleboy/ssh-action@v1.0.3
        with:
          passphrase: ${{ secrets.SSH_PASSPHRASE }}
          host: ${{ vars.REMOTE_HOST }}
          username: ${{ vars.REMOTE_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd gump
            echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u gump-ci --password-stdin
            echo COMMIT_SHA=${{github.sha}} > .env
            docker-compose -f docker-compose-dev.yml down
            docker-compose -f docker-compose-dev.yml up -d --build
