name: Build and deploy micro-services

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    defaults:
      run:
        working-directory: drtss-ms
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - run: ls
    
    - name: Build drtss-ms
      run: mvn clean install

    - name: build-docker-image
      run: docker build -t gump-drtss . && docker tag gump-drtss kulturman/gump-drtss:latest
