name: drtss
services:
  postgresql:
    image: postgres:16.4
    volumes:
      - drtss-data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=gump
      - POSTGRES_PASSWORD=gump
      - POSTGRES_HOST_AUTH_METHOD=trust
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U $${POSTGRES_USER}']
      interval: 5s
      timeout: 5s
      retries: 10
    ports:
      - 5431:5432

volumes:
    drtss-data:
